name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build and package
      run: npm run repack
      
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: release/*.zip
        generate_release_notes: true 